
import './globals.css'



export const metadata = {
  title: ' Next js App Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>Header</p>
        </header>
        {children}
        <footer>
          <p>footer</p>
        </footer>
        </body>
    </html>
  )
}
