
import Navbar from '@/components/shared/Navbar'
import './globals.css'
import Footer from '@/components/shared/Footer'



export const metadata = {
  title: ' Next js App Router',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <Navbar/>
        <div className='min-h-screen'>
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  )
}
